### ISSUE TITLE
User friendly navigation and responsive design

### ISSUE THREAD

**Issue by AJGreaves** [Code-Institute-Solutions/project-planning#8]
**User story**

As a First-Time Visitor, I need easy navigation and a user-friendly design, including a responsive layout for my device, so I can find information quickly and efficiently without frustration.

**Acceptance Criteria**

- [ ] The website is fully responsive across various devices and screen sizes.
- [ ] Site layout and navigation are intuitive, allowing easy access to different sections.

**Tasks**

- [ ] Apply responsive design principles using Bootstrap to ensure the website is accessible on various devices.
- [ ] Arrange the site layout and navigation based on best practices, ensuring all key sections and pages are easily accessible.
